"""
PDF Report Generator for Credit Rating Simulator — CORE Rating Criteria v3.0

Renders a PDF credit rating rationale report laid out like a published CRA rating
rationale: a ratings summary block, a prose rationale narrative (not slide bullets),
key financial/covenant tables, rating sensitivities, grounded methodology citations,
and an analytical contacts / disclaimer footer block. The document has no running
page headers or footers -- it reads as continuous content.
"""

import csv
import io
import os
import re
from datetime import date
from typing import Dict, Any, List, Optional
from xml.sax.saxutils import escape
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)

MANDATORY_DISCLAIMER = (
    "This is an indicative, academic assessment produced for an ICAI AICA Level 2 capstone project. "
    "It is not a credit rating issued by a registered credit rating agency and must not be relied upon as one."
)

REGULATORY_DISCLAIMER = (
    "Ratings and scores produced by this simulator are indicative only and are not the opinion of "
    "creditworthiness of any credit rating agency recognized by SEBI, RBI, or any other regulator. "
    "This report must not be used or relied upon for any investment, lending, procurement, or "
    "regulatory decision."
)

TECH_TYPE_LABELS = {
    "TECH_SOLAR": "Solar",
    "TECH_WIND": "Wind",
    "TECH_HYBRID": "Hybrid",
}

# Long-form labels for report narrative text (masthead, prose). Kept separate from
# TECH_TYPE_LABELS above, which stays short for use in the export filename.
TECH_TYPE_DISPLAY_LABELS = {
    "TECH_SOLAR": "Solar PV",
    "TECH_WIND": "Wind Power",
    "TECH_HYBRID": "Wind Solar Hybrid",
}

_UNSAFE_FILENAME_CHARS = re.compile(r'[\\/:*?"<>|]')

CORPUS_DIR = os.path.join(os.path.dirname(__file__), "..", "corpus")
CORPUS_DISPLAY_NAMES_PATH = os.path.join(CORPUS_DIR, "Corpus_Display_Names_v3_0.csv")
_CORPUS_DISPLAY_NAMES: Dict[str, str] = {}


def _load_corpus_display_names() -> None:
    global _CORPUS_DISPLAY_NAMES
    if _CORPUS_DISPLAY_NAMES:
        return
    if os.path.exists(CORPUS_DISPLAY_NAMES_PATH):
        with open(CORPUS_DISPLAY_NAMES_PATH, "r", encoding="utf-8") as f:
            for row in csv.DictReader(f):
                fname = (row.get("filename") or "").strip()
                disp = (row.get("display_name") or "").strip()
                if fname and disp:
                    _CORPUS_DISPLAY_NAMES[fname] = disp


def get_corpus_display_names() -> Dict[str, str]:
    """Public accessor for the loaded filename -> display-name table, e.g. for serving via the API."""
    _load_corpus_display_names()
    return dict(_CORPUS_DISPLAY_NAMES)


def humanize_corpus_filename(filename: str) -> str:
    """
    Looks up the human-readable title for a corpus filename from
    corpus/Corpus_Display_Names_v3_0.csv (generated by
    scratch/generate_corpus_display_names.py). Falls back to a mechanical
    underscore-to-space transform for any filename not yet in that table
    (e.g. a corpus file added since the table was last regenerated).
    """
    if not filename:
        return ""
    _load_corpus_display_names()
    if filename in _CORPUS_DISPLAY_NAMES:
        return _CORPUS_DISPLAY_NAMES[filename]
    name = re.sub(r"\.[A-Za-z0-9]+$", "", filename)
    name = re.sub(r"_{2,}", " ", name)
    name = name.replace("_", " ")
    return re.sub(r"\s+", " ", name).strip()


def _esc(val: Any) -> str:
    """Escapes XML special characters (&, <, >) for ReportLab Paragraph rendering."""
    if val is None:
        return ""
    return escape(str(val))


def _sanitize_filename_component(value: str) -> str:
    return _UNSAFE_FILENAME_CHARS.sub("", str(value)).strip()


def build_rationale_filename(project_id: str, project_data: Dict[str, Any]) -> str:
    """
    Builds the default/suggested export filename: "<Company Name>_<Technology>_<Capacity>.pdf",
    pulled from the project's extracted/entered data and sanitized for filesystem-safe characters.
    """
    company = _sanitize_filename_component(project_data.get("project_name") or project_id or "Project")

    tech_code = project_data.get("technology_type")
    tech = _sanitize_filename_component(TECH_TYPE_LABELS.get(tech_code, tech_code or "Technology"))

    capacity_val = project_data.get("installed_capacity_mw_ac")
    try:
        capacity_num = float(capacity_val)
    except (TypeError, ValueError):
        capacity_num = None

    if capacity_num is not None:
        capacity = f"{int(capacity_num) if capacity_num.is_integer() else capacity_num}MW"
    else:
        capacity = "Capacity"

    return f"{company}_{tech}_{capacity}.pdf"


def _total_debt_lakhs(project_data: Dict[str, Any]) -> Optional[float]:
    total_debt = project_data.get("total_debt")
    if total_debt is not None:
        return total_debt
    debt_instruments = project_data.get("debt_instruments")
    if isinstance(debt_instruments, list) and debt_instruments:
        return sum(
            inst.get("amount", 0) for inst in debt_instruments
            if isinstance(inst, dict) and inst.get("treatment") == "TREATMENT_DEBT"
        )
    return None


def generate_rationale_pdf(project_id: str, project_data: Dict[str, Any], score_result: Dict[str, Any]) -> bytes:
    """
    Generates a PDF credit rating rationale report from project inputs and score results.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=56,
        rightMargin=56,
        topMargin=56,
        bottomMargin=56
    )

    styles = getSampleStyleSheet()

    masthead_style = ParagraphStyle(
        "Masthead",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#475569"),
        spaceAfter=2,
    )
    title_style = ParagraphStyle(
        "DocTitle",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=colors.HexColor("#0F172A"),
    )
    meta_style = ParagraphStyle(
        "DocMeta",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#475569"),
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=14,
        spaceAfter=6,
    )
    sub_heading = ParagraphStyle(
        "SubHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#1E293B"),
        spaceBefore=8,
        spaceAfter=3,
    )
    body_style = ParagraphStyle(
        "BodyTextCustom",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        alignment=TA_JUSTIFY,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "BulletTextCustom",
        parent=body_style,
        alignment=TA_JUSTIFY,
        leftIndent=12,
        spaceAfter=3,
    )
    footer_heading_style = ParagraphStyle(
        "FooterHeading",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=10,
        spaceAfter=2,
    )
    footer_text_style = ParagraphStyle(
        "FooterText",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#475569"),
    )
    disclaimer_style = ParagraphStyle(
        "DisclaimerText",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=7.5,
        leading=10.5,
        textColor=colors.HexColor("#64748B"),
    )

    story: List[Any] = []

    # --- Masthead (document content, not a running page header) ---
    p_name = _esc(project_data.get("project_name") or project_id)
    tech_code = project_data.get("technology_type")
    tech_label = TECH_TYPE_DISPLAY_LABELS.get(tech_code, _esc(tech_code) or "N/A")
    cap = project_data.get("installed_capacity_mw_ac")
    cap_str = f"{cap} MW" if cap is not None else "N/A"
    pid_esc = _esc(project_id)
    today_str = date.today().strftime("%d %B %Y")

    story.append(Paragraph("CREDIT RATING SIMULATOR &nbsp;|&nbsp; RATING RATIONALE", masthead_style))
    story.append(Paragraph(p_name, title_style))
    story.append(Spacer(1, 3))
    story.append(Paragraph(
        f"Technology: {tech_label} &nbsp;|&nbsp; Installed Capacity: {cap_str} &nbsp;|&nbsp; "
        f"Project ID: {pid_esc} &nbsp;|&nbsp; Report Date: {today_str}",
        meta_style
    ))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#0F172A")))
    story.append(Spacer(1, 10))

    rationale_obj = score_result.get("rationale", {})
    if isinstance(rationale_obj, dict):
        exec_summary = _esc(rationale_obj.get("executive_summary", ""))
        blk_a_narr = _esc(rationale_obj.get("block_a_narrative", ""))
        blk_b_narr = _esc(rationale_obj.get("block_b_narrative", ""))
        blk_c_narr = _esc(rationale_obj.get("block_c_narrative", ""))
        blk_d_narr = _esc(rationale_obj.get("block_d_narrative", ""))
        sensitivities = rationale_obj.get("rating_sensitivities", {})
        citations = rationale_obj.get("citations", [])
    else:
        exec_summary = _esc(str(rationale_obj) if rationale_obj else "")
        blk_a_narr, blk_b_narr, blk_c_narr, blk_d_narr = "", "", "", ""
        sensitivities = {}
        citations = []

    ind_band = _esc(score_result.get("indicative_band", "N/A"))
    final_band = _esc(score_result.get("final_band", "N/A"))
    post_score = score_result.get("post_notching_score")
    raw_score = score_result.get("raw_score")
    confidence = _esc(score_result.get("confidence", "N/A"))
    conf_reason = _esc(score_result.get("confidence_reason", ""))
    cap_notice = _esc(score_result.get("cap_notice")) if score_result.get("cap_notice") else ""

    score_str = f"{post_score:.1f} / 115.0" if post_score is not None else "N/A"
    raw_str = f"{raw_score:.1f}" if raw_score is not None else "N/A"

    total_debt_raw = _total_debt_lakhs(project_data)
    try:
        total_debt = float(total_debt_raw)
    except (TypeError, ValueError):
        total_debt = None
    amount_str = f"Rs. {total_debt:,.1f} Lakhs" if total_debt is not None else "Not Disclosed"

    # --- Ratings Summary Block (CRA-style instrument/rating box) ---
    story.append(Paragraph("Ratings", section_heading))
    summary_header = ["Instrument / Facility", "Rated Amount", "Rating Assigned", "Confidence"]
    summary_row = [
        Paragraph("Senior Project Debt Facility (SPV)", body_style),
        Paragraph(amount_str, body_style),
        Paragraph(f"<b>{final_band}</b>", body_style),
        Paragraph(confidence, body_style),
    ]
    ratings_table = Table([summary_header, summary_row], colWidths=[168, 118, 118, 100])
    ratings_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(ratings_table)
    story.append(Spacer(1, 4))
    story.append(Paragraph(
        f"Indicative (pre-cap) band: {ind_band} &nbsp;|&nbsp; Raw score: {raw_str} / 115.0 &nbsp;|&nbsp; "
        f"Post-notching score: {score_str}",
        footer_text_style
    ))

    if cap_notice:
        story.append(Spacer(1, 6))
        cap_box = Table(
            [[Paragraph(f"<b>RATING CAP NOTICE:</b> {cap_notice}", body_style)]],
            colWidths=[504]
        )
        cap_box.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor("#94A3B8")),
            ('TOPPADDING', (0, 0), (-1, -1), 7),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        story.append(cap_box)

    story.append(Spacer(1, 6))

    # --- Rationale (continuous prose narrative) ---
    story.append(Paragraph("Rationale", section_heading))
    if exec_summary:
        story.append(Paragraph(exec_summary, body_style))

    story.append(Paragraph("Key Rating Drivers", sub_heading))
    if blk_a_narr:
        story.append(Paragraph(f"<b>Business &amp; Asset Risk.</b> {blk_a_narr}", body_style))
    if blk_b_narr:
        story.append(Paragraph(f"<b>Cash-Flow Adequacy &amp; Coverage.</b> {blk_b_narr}", body_style))
    if blk_c_narr:
        story.append(Paragraph(f"<b>Financial Strength &amp; Liquidity.</b> {blk_c_narr}", body_style))
    if blk_d_narr:
        story.append(Paragraph(f"<b>Structural &amp; Covenant Protections.</b> {blk_d_narr}", body_style))

    # --- Key Financial & Covenant Metrics ---
    min_dscr = score_result.get("minimum_dscr")
    avg_dscr = score_result.get("average_dscr")
    plcr_val = score_result.get("plcr")
    llcr_val = score_result.get("llcr")
    gearing_val = score_result.get("gearing")
    dsra_months_val = score_result.get("dsra_months")

    def _fmt_x(v):
        return f"{v:.2f}x" if isinstance(v, (int, float)) else "N/A"

    def _fmt_months(v):
        return f"{v:.1f} months" if isinstance(v, (int, float)) else "N/A"

    metrics_rows = [
        ["Metric", "Value", "Metric", "Value"],
        ["Minimum DSCR", _fmt_x(min_dscr), "Average DSCR", _fmt_x(avg_dscr)],
        ["Project Life Coverage Ratio (PLCR)", _fmt_x(plcr_val), "Loan Life Coverage Ratio (LLCR)", _fmt_x(llcr_val)],
        ["Total Debt / Tangible Net Worth (Gearing)", _fmt_x(gearing_val), "DSRA Coverage", _fmt_months(dsra_months_val)],
    ]
    story.append(Paragraph("Key Financial &amp; Covenant Metrics", sub_heading))
    metrics_table = Table(metrics_rows, colWidths=[168, 86, 168, 82])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#FAFAFA")]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(metrics_table)
    story.append(Spacer(1, 6))

    # --- Score Summary by CORE Rating Block ---
    blk_a = score_result.get("block_a_score")
    blk_b = score_result.get("block_b_score")
    blk_c = score_result.get("block_c_score")
    blk_d = score_result.get("block_d_score")

    breakdown_data = [
        ["CORE Rating Block", "Max Points", "Score Achieved", "% Score"],
        ["Block A: Business & Asset Risk", "35.0", f"{blk_a:.1f}" if blk_a is not None else "N/A", f"{(blk_a/35.0*100):.1f}%" if blk_a is not None else "N/A"],
        ["Block B: Cash-flow Adequacy & Coverage", "35.0", f"{blk_b:.1f}" if blk_b is not None else "N/A", f"{(blk_b/35.0*100):.1f}%" if blk_b is not None else "N/A"],
        ["Block C: Financial Strength & Liquidity", "25.0", f"{blk_c:.1f}" if blk_c is not None else "N/A", f"{(blk_c/25.0*100):.1f}%" if blk_c is not None else "N/A"],
        ["Block D: Structural & Covenant Protections", "20.0", f"{blk_d:.1f}" if blk_d is not None else "N/A", f"{(blk_d/20.0*100):.1f}%" if blk_d is not None else "N/A"],
    ]

    # Reconciliation row: the four block rows above sum to raw_score, but the Total row below
    # shows post_notching_score. Without a bridging row the table looks internally inconsistent
    # whenever a notch was actually applied. The engine always includes one entry per notching
    # category it evaluated -- even categories that triggered no notch (notches=0, points=0.0) --
    # so a plain "if notches_applied" truthy check would show this row even when nothing was
    # actually notched (confirmed against live TP-1/TP-2 output, which each carry exactly one
    # such zero-value entry). Only render it when at least one entry had real effect.
    notches_applied = score_result.get("notches_applied") or []
    active_notches = [n for n in notches_applied if (n.get("notches") or 0) < 0 or (n.get("points") or 0) < 0]
    if active_notches and raw_score is not None and post_score is not None:
        # Our engine's notches_applied[].points are already signed as negative deductions
        # (e.g. -7.0), unlike a positive-magnitude convention -- sum them directly.
        raw_notch_points = sum(n.get("points", 0) for n in notches_applied)
        floored = (raw_score + raw_notch_points) < 0
        notch_delta = post_score - raw_score

        detail = f"{raw_notch_points:.1f} pts"
        if floored:
            detail += " (floored at 0)"

        breakdown_data.append(["Notching Adjustment", "—", f"{notch_delta:.1f}", detail])

    breakdown_data.append(
        ["Total Post-Notching Score", "115.0", f"{post_score:.1f}" if post_score is not None else "N/A", f"{(post_score/115.0*100):.1f}%" if post_score is not None else "N/A"]
    )
    story.append(Paragraph("Score Summary by CORE Rating Block", sub_heading))
    breakdown_table = Table(breakdown_data, colWidths=[234, 90, 90, 90])
    breakdown_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#F1F5F9")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8.5),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor("#FAFAFA")]),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor("#E2E8F0")),
        ('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(breakdown_table)

    # --- Rating Sensitivities ---
    pos_factors = [_esc(f) for f in sensitivities.get("positive_factors", [])] if isinstance(sensitivities, dict) else []
    neg_factors = [_esc(f) for f in sensitivities.get("negative_factors", [])] if isinstance(sensitivities, dict) else []

    if pos_factors or neg_factors:
        story.append(Paragraph("Rating Sensitivities", section_heading))

        if pos_factors:
            story.append(Paragraph("Factors that could lead to a rating upgrade:", sub_heading))
            for f_text in pos_factors:
                story.append(Paragraph(f"&#8226; {f_text}", bullet_style))

        if neg_factors:
            story.append(Paragraph("Factors that could lead to a rating downgrade:", sub_heading))
            for f_text in neg_factors:
                story.append(Paragraph(f"&#8226; {f_text}", bullet_style))

    # --- Methodology Citations & Grounding ---
    if citations:
        story.append(Paragraph("Basis of Rating &amp; Methodology References", section_heading))
        for c in citations:
            doc_name = _esc(humanize_corpus_filename(c.get("source_document", "")))
            sec_name = _esc(c.get("source_section", ""))
            claim_text = _esc(c.get("display_claim") or c.get("claim", ""))
            cit_line = f"&#8226; <b>{doc_name} &mdash; {sec_name}</b>: {claim_text}"
            story.append(Paragraph(cit_line, bullet_style))

    story.append(Spacer(1, 12))
    story.append(HRFlowable(width="100%", thickness=0.75, color=colors.HexColor("#CBD5E1")))

    # --- Analytical Contacts / Disclaimer footer block (CRA-style, no running page footer) ---
    story.append(Paragraph("Analytical Contact", footer_heading_style))
    story.append(Paragraph(
        "Credit Rating Simulator Engine &mdash; CORE Rating Criteria v3.0 (automated deterministic scorecard). "
        "For methodology queries, refer to the published CRA criteria documents cited above.",
        footer_text_style
    ))
    story.append(Paragraph("Disclaimer", footer_heading_style))
    story.append(Paragraph(_esc(MANDATORY_DISCLAIMER), disclaimer_style))
    story.append(Paragraph(_esc(REGULATORY_DISCLAIMER), disclaimer_style))

    doc.build(story)
    return buffer.getvalue()
